### PR TITLE
Style suggestions for readability

### PR DESCRIPTION
**Pull request by gsong**
Minor style suggestions.

Don't worry, I'm not a style zealot. And we can use a linter to decide what we like.

### CODE REVIEW

**Comment by amymok** [comment]
The `urls.py` looks uglier though!

**Comment by amymok** [comment]
But that's good for now

**Comment by gsong** [comment]
I've definitely been influenced by the JavaScript community around that style. To me the reason is that `path()` invocation is noise, and what you really care about when you're scanning are the params to `path`.

But like I said, I'm not set on it.

**Comment by amymok** [comment]
Ah!  Yea I am definitely flexible as well.

**Pull request merged**
